apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exampleonechart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: charts/onechart
    repoURL: https://github.com/manuecascopeebles/onechart.git
    targetRevision: HEAD
    helm:
      version: v3
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

